### ISSUE TITLE
Building SyntaxNet

### ISSUE THREAD

**Issue by elizlee** [elizlee/Dependency-Parsing#1]
I am attempting to install SyntaxNet so that I can run [Parsey Universal](https://github.com/tensorflow/models/blob/master/research/syntaxnet/g3doc/universal.md). I have been following the instructions [here](https://github.com/tensorflow/models/tree/master/research/syntaxnet), but I am stuck at the `bazel test` step.

I believe the error that terminates the test is here:
(edit: added max 10 lines on either side of original code block)
```
WARNING: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/protobuf_archive/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
WARNING: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@grpc); this will cause a build error in future versions
WARNING: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/BUILD:1943:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/BUILD:1943:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/BUILD:1943:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/org_tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/org_tensorflow/tensorflow/contrib/learn/BUILD:17:1: in py_library rule @org_tensorflow//tensorflow/contrib/learn:learn: target '@org_tensorflow//tensorflow/contrib/learn:learn' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Analysed 281 targets (269 packages loaded).
INFO: Found 211 targets and 70 test targets...
ERROR: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/org_tensorflow/tensorflow/python/BUILD:4990:1: Executing genrule @org_tensorflow//tensorflow/python:framework/fast_tensor_util.pyx_cython_translation failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/bazel-sandbox/7207072300278808372/execroot/__main__/bazel-out/host/bin/external/cython/cython_binary.runfiles/__main__/../cython/cython.py", line 17, in <module>
    main(command_line = 1)
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/Main.py", line 720, in main
    result = compile(sources, options)
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/Main.py", line 695, in compile
    return compile_multiple(source, options)
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/Main.py", line 666, in compile_multiple
    context = options.create_context()
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/Main.py", line 590, in create_context
    self.cplus, self.language_level, options=self)
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/Main.py", line 75, in __init__
    from . import Builtin, CythonScope
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/Visitor.py", line 15, in <module>
    from . import ExprNodes
  File "/private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/cython/Cython/Compiler/ExprNodes.py", line 2875
    await = None
          ^
SyntaxError: invalid syntax
INFO: Elapsed time: 33.804s, Critical Path: 1.41s
FAILED: Build did NOT complete successfully
//dragnn/components/stateless:stateless_component_test                NO STATUS
//dragnn/components/syntaxnet:syntaxnet_component_test                NO STATUS
//dragnn/components/syntaxnet:syntaxnet_link_feature_extractor_test   NO STATUS
//dragnn/components/syntaxnet:syntaxnet_transition_state_test         NO STATUS
//dragnn/core:beam_test                                               NO STATUS
//dragnn/core:compute_session_impl_test                               NO STATUS
//dragnn/core:compute_session_pool_test                               NO STATUS
//dragnn/core:dragnn_bulk_op_kernels_test                             NO STATUS
```
It seems like it has something to do with Cython, although I'm not sure how to move forward from here.

I am using Bazel version 0.11.1 per the instructions. Could it be a matter of installing a more recent version?

**Comment by berquist** [comment]
A `SyntaxError` on `await` screams Python 3.6 vs. 3.7 error. Which version of Python are you using?

**Comment by elizlee** [comment]
@berquist 3.7

**Comment by berquist** [comment]
`await` is Python syntax in 3.7, and https://github.com/tensorflow/models/blob/master/research/syntaxnet/README.md#manual-installation says it's 2.7 only. You should be able to pass `python=2.7` to `conda create` to automatically create a conda environment with the right Python version.

**Comment by elizlee** [comment]
I am now running this in a 2.7 conda environment, and I get a new error.
```
INFO: Analysed 281 targets (0 packages loaded).
INFO: Found 211 targets and 70 test targets...
ERROR: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/grpc/BUILD:1287:1: C++ compilation of rule '@grpc//:grpc_resolver_dns_ares' failed (Exit 1)
external/grpc/src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc:30:10: fatal error: 'ares.h' file not found
#include <ares.h>
         ^~~~~~~~
1 error generated.
INFO: Elapsed time: 19.577s, Critical Path: 9.74s
FAILED: Build did NOT complete successfully
```

**Comment by berquist** [comment]
Hm, I don't even get that far:
```
Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See tools/bazel.rc for more details.
        --config=mkl            # Build with MKL support.
        --config=monolithic     # Config for mostly static monolithic build.
Configuration finished
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/Users/berquist/repositories/models/research/syntaxnet/tools/bazel.rc
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
ERROR: /Users/berquist/repositories/models/research/syntaxnet/WORKSPACE:10:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
ERROR: Skipping '../..': Bad target pattern '../..': package name component contains only '.' characters
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
INFO: Elapsed time: 16.570s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/Users/berquist/repositories/models/research/syntaxnet/tools/bazel.rc
ERROR: /Users/berquist/repositories/models/research/syntaxnet/WORKSPACE:10:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.060s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by elizlee** [comment]
Which version of Bazel are you using? I got those when I had 0.28.0 installed.

**Comment by berquist** [comment]
0.28, naturally...

**Comment by elizlee** [comment]
The instructions specify 0.11.1, although I have seen others say they were successful with some of the later ones, like 0.19.2.

**Comment by berquist** [comment]
I've downloaded 0.11.1 and things are compiling normally after accepting all the defaults from `configure`. The difference must be in our Homebrew environments, because I didn't need to apply the fix from https://github.com/tensorflow/tensorflow/issues/19464.

What is your output from `pip freeze`
```
asciitree==0.3.3
autograd==1.1.13
certifi==2019.6.16
funcsigs==1.0.2
future==0.17.1
mock==3.0.5
numpy==1.16.4
protobuf==3.3.0
pygraphviz==1.5
six==1.12.0
```
and `conda list`?
```
# packages in environment at /Users/berquist/.anaconda/envs/syntaxnet:
#
# Name                    Version                   Build  Channel
asciitree                 0.3.3                    pypi_0    pypi
autograd                  1.1.13                   pypi_0    pypi
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_1    conda-forge
funcsigs                  1.0.2                    pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
libcxx                    8.0.0                         4    conda-forge
libcxxabi                 8.0.0                         4    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
mock                      3.0.5                    pypi_0    pypi
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.16.4                   pypi_0    pypi
openssl                   1.1.1c               h01d97ff_0    conda-forge
pip                       19.1.1                   py27_0    conda-forge
protobuf                  3.3.0                    pypi_0    pypi
python                    2.7.15            hd51d24c_1009    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                41.0.1                   py27_0    conda-forge
six                       1.12.0                   pypi_0    pypi
sqlite                    3.29.0               hb7d70f7_0    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
wheel                     0.33.4                   py27_0    conda-forge
zlib                      1.2.11            h01d97ff_1005    conda-forge
```

Here is how I made the env:
```bash
conda create -y -n syntaxnet python=2.7
conda activate syntaxnet
pip install protobuf==3.3.0 autograd==1.1.13 mock asciitree numpy
```

---

Another thing I misread was
```
  bazel test ...
  # On Mac, run the following:
  bazel test --linkopt=-headerpad_max_install_names \
    dragnn/... syntaxnet/... util/utf8/...
```
which really means to do
```
bazel test --linkopt=-headerpad_max_install_names dragnn/... syntaxnet/... util/utf8/...
```

**Comment by elizlee** [comment]
`pip freeze`:
```
asciitree==0.3.3
autograd==1.1.13
certifi==2019.6.16
funcsigs==1.0.2
future==0.17.1
graphviz==0.11.1
mock==3.0.5
numpy==1.16.4
protobuf==3.3.0
pygraphviz==1.5
six==1.12.0
```
`conda list`:
```
# packages in environment at /Users/isiboston/miniconda3/envs/syntaxnet:
#
# Name                    Version                   Build  Channel
asciitree                 0.3.3                    pypi_0    pypi
autograd                  1.1.13                   pypi_0    pypi
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py27_1    conda-forge
funcsigs                  1.0.2                    pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
libcxx                    8.0.0                         4    conda-forge
libcxxabi                 8.0.0                         4    conda-forge
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
mock                      3.0.5                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1
numpy                     1.16.4                   pypi_0    pypi
openssl                   1.1.1c               h01d97ff_0    conda-forge
pip                       19.1.1                   py27_0
protobuf                  3.3.0                    pypi_0    pypi
pygraphviz                1.5                      pypi_0    pypi
python                    2.7.15            hd51d24c_1009    conda-forge
python-graphviz           0.11.1                   pypi_0    pypi
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                41.0.1                   py27_0
six                       1.12.0                   pypi_0    pypi
sqlite                    3.29.0               ha441bb4_0
tk                        8.6.9             h2573ce8_1002    conda-forge
wheel                     0.33.4                   py27_0
zlib                      1.2.11               h1de35cc_3
```
And I get this now:
```
ERROR: /private/var/tmp/_bazel_isiboston/a93a4c20881ba5c4c29b706e5b836e99/external/org_tensorflow/tensorflow/python/BUILD:4990:1: C++ compilation of rule '@org_tensorflow//tensorflow/python:framework/fast_tensor_util.so' failed (Exit 1)
In file included from bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:531:
In file included from bazel-out/host/genfiles/external/local_config_python/numpy_include/numpy/arrayobject.h:4:
In file included from bazel-out/host/genfiles/external/local_config_python/numpy_include/numpy/ndarrayobject.h:12:
In file included from bazel-out/host/genfiles/external/local_config_python/numpy_include/numpy/ndarraytypes.h:1822:
bazel-out/host/genfiles/external/local_config_python/numpy_include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9007:21: error: no member named 'exc_type' in '_ts'
    *type = tstate->exc_type;
            ~~~~~~  ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9008:22: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
    *value = tstate->exc_value;
                     ^~~~~~~~~
                     curexc_value
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:240:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9009:19: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
    *tb = tstate->exc_traceback;
                  ^~~~~~~~~~~~~
                  curexc_traceback
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:241:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9016:24: error: no member named 'exc_type' in '_ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9017:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:240:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9018:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:241:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9019:13: error: no member named 'exc_type' in '_ts'
    tstate->exc_type = type;
    ~~~~~~  ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9020:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
    tstate->exc_value = value;
            ^~~~~~~~~
            curexc_value
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:240:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9021:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
    tstate->exc_traceback = tb;
            ^~~~~~~~~~~~~
            curexc_traceback
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:241:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9091:24: error: no member named 'exc_type' in '_ts'
    tmp_type = tstate->exc_type;
               ~~~~~~  ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9092:25: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
    tmp_value = tstate->exc_value;
                        ^~~~~~~~~
                        curexc_value
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:240:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9093:22: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
    tmp_tb = tstate->exc_traceback;
                     ^~~~~~~~~~~~~
                     curexc_traceback
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:241:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9094:13: error: no member named 'exc_type' in '_ts'
    tstate->exc_type = local_type;
    ~~~~~~  ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9095:13: error: no member named 'exc_value' in '_ts'; did you mean 'curexc_value'?
    tstate->exc_value = local_value;
            ^~~~~~~~~
            curexc_value
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:240:15: note: 'curexc_value' declared here
    PyObject *curexc_value;
              ^
bazel-out/host/genfiles/external/org_tensorflow/tensorflow/python/framework/fast_tensor_util.cpp:9096:13: error: no member named 'exc_traceback' in '_ts'; did you mean 'curexc_traceback'?
    tstate->exc_traceback = local_tb;
            ^~~~~~~~~~~~~
            curexc_traceback
bazel-out/host/genfiles/external/local_config_python/python_include/pystate.h:241:15: note: 'curexc_traceback' declared here
    PyObject *curexc_traceback;
              ^
1 warning and 15 errors generated.
INFO: Elapsed time: 6.598s, Critical Path: 5.79s
FAILED: Build did NOT complete successfully
```

**Comment by elizlee** [comment]
Update: installed gcc and libgcc (4.8.5), and I am back at the `'ares.h' file not found` error again...

**Comment by berquist** [comment]
I'll keep attacking, but I think Liz and Constantine did most of their testing with the Docker. Would the Docker work for your use case?

**Comment by elizlee** [comment]
I could try it out.

**Comment by berquist** [comment]
Adding `--define=grpc_no_ares=true` as mentioned in https://github.com/tensorflow/tensorflow/issues/19464#issuecomment-460707647 seems to fixed that problem. If you can't use the Docker and need to build from source, try that.

Things I did before building again:
- `\rm -rf /private/var/tmp/_bazel_isiboston`
- `cd models/research/syntaxnet/tensorflow; git clean -xdf .`
- `cd ..; git clean -xdf .`

to remove all the old Bazel files.

Though now I get
```
ERROR: /Users/berquist/repositories/models/research/syntaxnet/util/utf8/BUILD:5:1: C++ compilation of rule '//util/utf8:unicodetext' failed (Exit 1)
In file included from util/utf8/unicodetext.cc:17:
In file included from ./util/utf8/unicodetext.h:25:
./syntaxnet/base.h:25:10: fatal error: 'google/protobuf/util/message_differencer.h' file not found
#include "google/protobuf/util/message_differencer.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
might be related to
```
WARNING: /private/var/tmp/_bazel_berquist/093c783573852100119e60a8e84024ed/external/protobuf_archive/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_berquist/093c783573852100119e60a8e84024ed/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build
 error in future versions
```
from earlier in my build.

**Comment by elizlee** [comment]
The [Parsey Universal Server](https://github.com/andersrye/parsey-universal-server) is working for me, so hopefully I can rely on this instead.
